#!/bin/sh

RESET="\033[0m"
FG_ALT="\033[30m"

BLACK="\033[40m"
RED="\033[41m"
GREEN="\033[42m"
YELLOW="\033[43m"
BLUE="\033[44m"
MAGENTA="\033[45m"
CYAN="\033[46m"
WHITE="\033[47m"

LBLACK="\033[100m"
LRED="\033[101m"
LGREEN="\033[102m"
LYELLOW="\033[103m"
LBLUE="\033[104m"
LMAGENTA="\033[105m"
LCYAN="\033[106m"
LWHITE="\033[107m"

show_help() {
	printf "Display ANSI colors or color codes.\n\n"
	printf "Usage: colors [option]\n\n"
	printf "Options:\n"
	printf "  -h, --help  Show this message and exit.\n"
	printf "  -c, --codes Show color codes.\n"
}

show_colors() {
	printf "${BLACK}   ${RED}   ${GREEN}   ${YELLOW}   ${BLUE}   ${MAGENTA}   ${CYAN}   ${WHITE}   \n"
	printf "${LBLACK}   ${LRED}   ${LGREEN}   ${LYELLOW}   ${LBLUE}   ${LMAGENTA}   ${LCYAN}   ${LWHITE}   ${RESET}\n"
}

show_color_codes() {
	printf "${BLACK} 30 ${RED} 31 ${GREEN}${FG_ALT} 32 ${YELLOW} 33 ${RESET}${BLUE} 34 ${MAGENTA} 35 ${CYAN}${FG_ALT} 36 ${WHITE} 37 ${RESET}\n"
	printf "${LBLACK} 40 ${LRED} 41 ${LGREEN}${FG_ALT} 42 ${LYELLOW} 43 ${RESET}${LBLUE} 44 ${LMAGENTA} 45 ${LCYAN}${FG_ALT} 46 ${LWHITE} 47 ${RESET}\n"
}

if [ "$1" = "-c" ] || [ "$1" = "--codes" ]; then
	show_color_codes
elif [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
	show_help
else
	show_colors
fi
