#!/bin/sh

MENU="fuzzel -d"

current_dir=$(xdg-user-dir PICTURES || echo "$HOME/Pictures")

list_items() {
	for item in "$current_dir"/*; do
		basename "$item"
	done
}

while true; do
	choice=$(list_items | $MENU)

	if [ -z "$choice" ]; then
		echo "Invalid or canceled option."
		exit 1
	fi

	selected_path="$current_dir/$choice"

	if [ -d "$selected_path" ]; then
		current_dir="$selected_path"
	elif [ -f "$selected_path" ]; then
		feh --bg-scale "$selected_path" 
	   	ln -sf "$selected_path" ~/wallpaper

		exit 0
	else
		echo "Invalid option."
	fi
done
